# Prerequisites ----
if (!require("tidyverse")) install.packages("tidyverse")
if (!require("googlesheets4")) install.packages("googlesheets4")

library(tidyverse)
library(googlesheets4)

# NOTE: Adapted from open-neuroscience's autopost.R adapted for use with Eventer

# Base Functions List ----

# create_yaml() will create the content in the YAML header
  create_yaml <- function(title, authors, categories, description){
    yaml_break <-"---"
    tit <- paste("title:", shQuote(title))
    dat <- paste("date:", Sys.Date())
    authors <- stringr::str_c(shQuote(authors), collapse=" , ")
    authors <- paste0("[", authors,"]")
    aut <- paste("authors:", authors)
    lay <- "layout: post"
    # categories come shQuoted properly from parse_tags()
    categories <- paste0("[", categories,"]")
    catt <- paste("categories:", categories)
    # tags are the same as categories for now...
    tagg <- paste("tags:", categories)
    # published by default to false, and should be checked on a local server
    pubb <- paste("published: false")
    summ <- paste("summary:", description)

    # make the yaml
    output <- paste(yaml_break,
                    tit,
                    dat,
                    aut,
                    lay,
                    catt,
                    tagg,
                    pubb,
                    summ,
                    yaml_break, sep = "\n")
    return(output)

  }



# create_body() will create the content under the YAML header
 create_body <- function(title,
                         description,
                         authors,
                         post_author,
                         institution,
                         prep,
                         rec_type,
                         cell_type,
                         temp,
                         intra,
                         extra,
                         contact,
                         social,
                         model_dl,
                         presets_dl,
                         DOI,
                         UID){
    # remove all spaces in title
    #title <- gsub(x = title , pattern = " ", replacement = "_")
    # remove all other punctuation things
    #title <- stringr::str_replace_all(string = title,
                                      #pattern="[[:punct:]]",
                                      #replacement="_")
    title <- UID
    # make folder on posts if it doesn't exist
    root = "content/post"
    if(title %in% list.files(root) == FALSE){
      # make dir
      dir.create(file.path(root, title))
    }
    # download image and return the new path
    # image <- get_image(image_link = image, path = file.path(root, title))
    # add the "![]()"
    # if the name is called "featured" we don't need to link to it in the post
    #image <- paste0("![](", image, ")")

    # bind things into "description"
      description <- paste("## Model Abstract:",
                           description,
                           "## Model Download:",
                           "[Download Model](",model_dl,")",
                           "## Presets Download:",
                           "[Download Presets](",presets_dl,")",
                           "## Author(s):",
                           "### Author",
                           authors,
                           "### Affiliation",
                           institution,
                           "### Contact",
                           contact,
                           "### Twitter",
                           social,
                           "## Experimental Methodology:",
                           "### Preparation",
                           prep,
                           "### Recording Type",
                           rec_type,
                           "### Cell Type",
                           cell_type,
                           "### Recording Temperature (celsius)",
                           temp,
                           "### Intracellular Solution",
                           intra,
                           "### Extracellular Solution",
                           extra,
                           "### Related DOI",
                           DOI,
                           #"## Project Links",
                           "***",
                           "This post was automatically generated by Team Eventer Admin  ",
                           "To cite this model please use the model UID:  ",
                           "eventerneuro.netlify.app/post/",UID,
                           sep="\n")

    # paste things
    output <- paste(
      # image,
      description,
      '***',
      sep="\n")
    return(output)
  }

# write_md() writes the actual markdown document
  write_md <- function(filename, content){
    fileConn <- file(filename)
    writeLines(content, fileConn)
    close(fileConn)
  }


# parse_tags will pull the tags from the google form and add to the md (in YAML)
  parse_tags <- function(df){
    df %>%
      select(starts_with(c("Preparation","Recording Type"))) %>%
      group_by(row=row_number()) %>%
      pivot_longer(cols = starts_with(c("Preparation","Recording Type"))) %>%
      filter(value != "NA") %>%
      summarise(categories = paste(shQuote(value), collapse=",")) %>%
      pull(categories)

  }

# Write index.md -----
  # get the file path (ensure .Rproj opened before entering here)
  filePath <- getwd()

  # this is the ID for the google sheet (found before /edit)
  ID <- "1HU5XmPhl5c0fyrpy7xPcLRfm4sFAjYFAtG5P81Bpx7c"
  target <- read_sheet(ID)

  # this comes handy for later,
  # so that we don't add a bunch of columns when we write back
  original_columns <- names(target)

  # append 'tags' to dataframe
  target$tags <- parse_tags(target)
  # do big changes

  # check if any submissions require posting - is this skipping if there's a false entry?
  #if (any(target$posted,na.rm = FALSE) != "TRUE") {

  # check if this random number exists and repeat if so
  rs <- "Example_Model"
  while (rs %in% list.files("content/post/") == TRUE) { rs <- stringi::stri_rand_strings(n=1, length=12, "[a-z0-9]") }

  # post_df simply won't be created if there's no values with FALSE
  post_df <- target %>%
    # this should now only look to post the not posted posts ...
    filter(is.na(posted)|posted==FALSE) %>%
    mutate(
      filename = file.path("content/post", rs, "index.md")) %>%
      # filename = file.path("content/post", rs, "index.md")) %>%
    # we could have repeated posts maybe worth to check in the future
    # distinct()
    # we need to apply the functions rowwise
    rowwise() %>%
    mutate(yaml = create_yaml(`Model Name`, `Experimenter(s)`, tags, `Model Description`),
           body = create_body(
             title = `Model Name`,
             description = `Model Description`,
             prep = `Preparation`,
             cell_type = `Cell Type`,
             rec_type = `Recording Type`,
             temp = `Recording Temperature (celsius)`,
             intra = `Intracellular Solution`,
             extra = `Extracellular Solution`,
             authors = `Experimenter(s)`,
             post_author = `Experimenter(s)`,
             institution = `Institution(s)`,
             contact = `Contact email`,
             social = `Twitter Handle`,
             model_dl = `Upload your model`,
             presets_dl = `Upload your presets`,
             DOI = `Related DOI`,
             UID = rs),
           post = paste(yaml, body, sep ="\n"))

  # actually write the md
  lapply(1:nrow(post_df), function(x) write_md(post_df$filename[x], post_df$post[x]))

  # create filename variable that's manipulated in the same way as the foldernames
  # this may be partially redundant as variable may be spat out in the above chunk


  # NOW NO NEED TO CHANGE THE FOLDERNAME
  #filename = gsub(x = post_df$`Model Name` , pattern = "[[:punct:]]", replacement = "_")
  #filename = gsub(x = filename , pattern = " ", replacement = "_")

  # check whether a folder exists for the new models (relative to the above filename)
  #target$posted <- str_replace_all(string = filename,
                                   #pattern = " ", replacement = "_") %in%
    #list.files("content/post/")

  #file.rename(file.path(filePath, "content/post", filename),
  #            file.path(filePath, "content/post", rs))

  post_df$UID <- rs # assign UID of the post
  target$UID[length(target$UID)] <- rs # change the last value to match the UID
  target$posted <- str_replace_all(string = target$UID,
                                   pattern = " ", replacement = "_") %in%
    list.files("content/post/")

  # overwrite the original!
  write_sheet(target %>% select(original_columns),ss = ID, sheet=1)

  # taking too much time to fix this now, so removed for the time being
  #} else {print("All submissions posted, put your feet up")}

  # USER NOW REQUIRED TO ...
        # CHECK ON LOCAL HOST
        # Change the published to `true` in the YAML front matter
        # COMMIT TO GITHUB


## DEVELOPMENT

#  x <- readline("Send automated email confirmation of post uploading? (Y/N): ")


#  if (x == "Y") {
#    print("Email sent")
#  } else {
#    print("Email not sent")
#    }
#if bug in lapply, unmute the following line
#file.path(getwd(),post_df$filename[1])

