# Prerequisites ----
if (!require("tidyverse")) install.packages("tidyverse")
if (!require("easycsv")) install.packages("easycsv")
if (!require("googlesheets4")) install.packages("googlesheets4")

library(tidyverse)
library(easycsv)
library(googlesheets4)

# NOTE: Adapted from open-neuroscience's autopost.R adapted for use with Eventer

# Base Functions List ----

# create_yaml() will create the content in the YAML header
  create_yaml <- function(title, authors, categories){
    yaml_break <-"---"
    tit <- paste("title:", shQuote(title))
    dat <- paste("date:", Sys.Date())
    authors <- stringr::str_c(shQuote(authors), collapse=" , ")
    authors <- paste0("[", authors,"]")
    aut <- paste("authors:", authors)
    lay <- "layout: post"
    # categories come shQuoted properly from parse_tags()
    categories <- paste0("[", categories,"]")
    catt <- paste("categories:", categories)
    # tags are the same as categories for now...
    tagg <- paste("tags:", categories)

    # make the yaml
    output <- paste(yaml_break,
                    tit,
                    dat,
                    aut,
                    lay,
                    catt,
                    tagg,
                    yaml_break, sep = "\n")
    return(output)

  }



# create_body() will create the content under the YAML header
 create_body <- function(title,
                         description,
                         authors,
                         post_author,
                         prep,
                         temp,
                         intra,
                         extra,
                         contact,
                         social){
    # remove all spaces in title
    title <- gsub(x = title , pattern = " ", replacement = "_")
    # remove all other punctuation things
    title <- stringr::str_replace_all(string = title,
                                      pattern="[[:punct:]]",
                                      replacement="_")
    # make folder on posts if it doesn't exist
    root = "content/post"
    if(title %in% list.files(root) == FALSE){
      # make dir
      dir.create(file.path(root, title))
    }
    # download image and return the new path
    # image <- get_image(image_link = image, path = file.path(root, title))
    # add the "![]()"
    # if the name is called "featured" we don't need to link to it in the post
    #image <- paste0("![](", image, ")")

    # bind things into "description"
      description <- paste("## Model Abstract:",
                           description,
                           "## Model Download:",
                           "*ADMIN: INSERT LINK HERE*",
                           "## Author(s):",
                           "### Author & Affiliation",
                           authors,
                           "### Contact",
                           contact,
                           "### Twitter",
                           social,
                           "## Experimental Methodology:",
                           "### Preparation",
                           prep,
                           "### Recording Temperature (celsius)",
                           temp,
                           "### Intracellular Solution",
                           intra,
                           "### Extracellular Solution",
                           extra,
                           #"## Project Links",
                           "***",
                           "This post was automatically generated by",
                           "Team Eventer Admin",
                           sep="\n")

    # paste things
    output <- paste(
      # image,
      description,
      '***',
      sep="\n")
    return(output)
  }



# get_image() uses the url provided to select an image for the post, if none provided or there are errors then own image will be used.
# get_image <- function(image_link, path){
#
#    # we will default to our logo when things are nasty on the image side
#    our_logo <- "https://github.com/eventer-neuroscience/eventer-fresh/blob/master/content/authors/admin/avatar.jpg?raw=true"
#    url <- case_when(str_detect(image_link, "png") ~ str_extract(image_link, ".+png"),
#                     str_detect(image_link, "jpg") ~ str_extract(image_link, ".+jpg"),
#                     str_detect(image_link, "gif") ~ str_extract(image_link, ".+gif"),
#                     # When it doesn't detect, we will fall back to the logo image
#                     TRUE ~ our_logo
#    )
#
#    filename <- case_when(
#      str_detect(image_link, "png") ~ file.path(path, "featured.png"),
#      str_detect(image_link, "jpg") ~ file.path(path, "featured.jpg"),
#      str_detect(image_link, "gif") ~ file.path(path, "featured.gif"),
#      # we need to fail with featured.jpg because our logo image is .jpg
#      TRUE ~ file.path(path, "featured.jpg")
#    )
#
#    if(url == our_logo){
#      write.table(paste("problem with", image_link),
#    # check whether there's a problem with the image
#                  file = paste0(tools::file_path_sans_ext(filename), ".txt"),
#    }
#
#    # if this thing is not an URL it will fail
#                  row.names = FALSE)
#    url <- download.file(url, filename, mode = "wb")
#
#    # check if the image can be loaded
#    img <- try(imager::load.image(filename))
#      write.table(paste("problem with", image_link),
#    if (class(img) == "try-error"){
#                  row.names = FALSE)
#                  file = paste0(tools::file_path_sans_ext(filename), ".txt"),
#      # move the logo into featured
#      file.copy("content/authors/admin/avatar.jpg",
#                filename,
#                overwrite = TRUE)
#
#    }
#
#    return(filename)
#  }


# write_md() writes the actual markdown document
  write_md <- function(filename, content){
    fileConn <- file(filename)
    writeLines(content, fileConn)
    close(fileConn)
  }


# parse_tags will pull the tags from the google form and add to the md (in YAML)
  parse_tags <- function(df){
    df %>%
      select(starts_with("Descriptive tags")) %>%
      group_by(row=row_number()) %>%
      pivot_longer(cols = starts_with("Descriptive")) %>%
      filter(value != "NA") %>%
      summarise(categories = paste(shQuote(value), collapse=",")) %>%
      pull(categories)

  }



# Write index.md -----

  # set wd to root of desired website (i think OS independent)
  setwd(easycsv::choose_dir())
  # get the new file path
  filePath <- getwd()

  # this is the ID for the google sheet (found before /edit)
  ID <- "1YguG_-nif4dyvxzHX6HyeNIeqyM7FSpyyKSKj9yVYrk"
  target <- read_sheet(ID)

  # this comes handy for later,
  # so that we don't add a bunch of columns when we write back
  original_columns <- names(target)

  # append 'tags' to dataframe
  target$tags <- parse_tags(target)
  # do big changes
  post_df <- target %>%
    filter(is.na(posted)|posted==FALSE) %>%
    mutate(
      # make filename
      filename = gsub(x = `Model Name` , pattern = " ", replacement = "_"),
      filename = file.path("content/post", filename, "index.md")) %>%
    # we could have repeated posts maybe worth to check in the future
    # distinct()
    # we need to apply the functions rowwise
    rowwise() %>%
    mutate(yaml = create_yaml(`Model Name`, `Experimenter & Institution`, tags),
           body = create_body(
             title = `Model Name`,
             description = `Model Description`,
             prep = `Preparation`,
             temp = `Recording Temperature (celsius)`,
             intra = `Intracellular Solution`,
             extra = `Extracellular Solution`,
             authors = `Experimenter & Institution`,
             post_author = `Experimenter & Institution`,
             contact = `Contact email`,
             social = `Twitter Handle`),
           post = paste(yaml, body, sep ="\n"))

  # actually write
  # known issue here if there's a full stop in the model name ... gsub functionality may be able to get round this, but for now just change on google sheet
  lapply(1:nrow(post_df), function(x) write_md(post_df$filename[x], post_df$post[x]))

  # change posted to TRUE on google sheets
  # I think it is safe to overwrite directly here

  # THIS SECTION NEEDS UPDATING!
  # Currently not actually writing to TRUE, can be done manually in the meantime.


  target$posted <- str_replace_all(string = target$`Model Name`,
                                   pattern = " ", replacement = "_") %in%
    list.files("/content/post/")

  # overwrite the original!
  write_sheet(target %>% select(original_columns),ss = ID, sheet=1)

